artifactoryPath: iow
dockerImageName: iow-geoserver
projectName: iow-allgemein
memory: 3072
cpu: 1024
applicationName: iow-geoserver
containerPort: 8080
healthCheck: /geoserver/web/
gitRepoUrl: https://github.com/usgs/iow-geoserver.git
gitRepoCredentialsId: GITHUB_ACCESS_TOKEN
listenerPort: 443
envVars:
  - name: GEOSERVER_DATA_DIR
    value: /data
mounts:
  - name: GEOSERVER_DATA_DIR_MOUNT
    source: /efs
    destination: /data
    readOnly: False
# configuration repository paths
configRepoPath: "wma/docker/iow/iow-geoserver"
configCredentialsId: "wma-eto-eb-rsa"
urlRules:
  - type: forward
    conditions:
      - "/geoserver/*"
    priority: 97
tags:
  wma:costCenter: "TBD"
  wma:organization: "nldi"
  wma:contact: "dblodgett@usgs.gov"
  wma:taggingVersion: "0.0.1"
  wma:project_id: "nldi"
